repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.11.13"
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
  - repo: https://github.com/commitizen-tools/commitizen
    rev: "v4.8.2"
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages: [commit-msg, pre-push]
